services:
  - type: web
    name: taskflow-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GOOGLE_CALLBACK_URL
        value: https://task-mana-ics6.onrender.com/api/auth/google/callback
      - key: CLIENT_URL
        value: https://task-manager-delta-liart.vercel.app
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: MONGODB_URI
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
